export const state = {
    api_route: 'https://jupiter-eg.com/admin-panel/public/api/',
    route: 'https://jupiter-eg.com/admin-panel/',
    SubmitOTP: null,
    AddedProductToCart: {},
    selectedAttribute: {},
    userData:null,
    settings:null,
    RemovedProduct: null,
    ProductsCategoryProducts: null,
    cart:null,
    product:null,
    wheelpoints:null,
    color:null,
    size:null,
    ResendOTP: null,
    ForgetPassword: null,
    Logout: null,
    banners: [],
    home_products: [],
    isAuthenticated: {},
    ResetPassword: null,
    Loading: {},
}

export default state